version: "3.7"
services:
  condado_supervisor_api:
    image: condado_supervisor_api:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: supervisor_api
    ports:
      - "8000:8000"
    volumes:
      - ./supervisor/api:/app
    #depends_on:
    #  - condado_supervisor_db
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
  #condado_supervisor_db:
  #  image: mongo:latest
  #  volumes:
  #    - ./supervisor/db:/data/db
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: condado
  #    MONGO_INITDB_ROOT_PASSWORD: condado
  condado_spa:
    image: condado_spa:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./spa:/app
    command: npm run dev -- --host
    ports:
      - "5143:5143"
      - "3000:3000"