version: "3.7"
services:
  # nginx
  condado_webserver:
    image: nginx:1.25.2
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    depends_on:
      - condado_spa
      - condado_supervisor_api
  # api
  condado_supervisor_api:
    image: condado_supervisor_api:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: supervisor_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./supervisor/api:/app
      - ./settings.env:/.condado/settings.env
      - ./tenents:/tenents
    depends_on:
      - condado_supervisor_db
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    environment:
      MONGO_HOST: condado_supervisor_db
      MONGO_PORT: 27017
      MONGO_DB: condado
      MONGO_USER: condado
      MONGO_PASSWORD: condado
  # mongo db
  condado_supervisor_db:
    image: mongo:latest
    volumes:
      - ./supervisor/db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: condado
      MONGO_INITDB_ROOT_PASSWORD: condado
      MONGO_INITDB_DATABASE: condado
  # vue
  condado_spa:
    image: condado_spa:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./spa:/app
    command: npm run dev -- --host
networks:
  default:
    name: condado
